language: java
notifications:
  slack:
    secure: armmk2zO/+66GKMtz08cNOb5bfIzpNnUvPXGxcZ7zjSkq21xRAdsNsD2WwjvB065PupI1Ej98dQ5ApyCluYHVQKqz0dqsLekilaNYdQVnzpW1d5/oZ0MxAEGRFm+ocCVPAyopHuI1QnC82HTn+uqCjhIEbtXwYsvymqllanZAxg=
