branch-defaults:
  master:
    environment: cakeredux-prod
environment-defaults:
  cakeredux-prod:
    branch: null
    repository: null
global:
  application_name: cakeredux
  default_ec2_keyname: javabin
  default_platform: 64bit Amazon Linux 2 v3.2.6 running Corretto 11
  default_region: eu-central-1
  profile: javabin
  sc: git
deploy:
  artifact: app.zip